# schedules:
#   - cron: '* 1 * * *'
#     displayName: 'Every day at 3am'
#     branches:
#       include: [main]
#     always: true

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      git config --global user.email 'bot@renovateapp.com'
      git config --global user.name 'Renovate Bot'
      npx renovate
    env:
      TOKEN: $(PAT)
      GITHUB_COM_TOKEN: $(PAT)
      RENOVATE_TOKEN: $(PAT)